[package]
name = "database_saver"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7.12", features = ["with-chrono-0_4"] }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5"
